return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  dependencies = {
    "windwp/nvim-ts-autotag",
    "JoosepAlviste/nvim-ts-context-commentstring",
  },
  opts = {
    ensure_installed = {
      "python",
      "lua",
      "json",
      "yaml",
      "go",
      "rust",
      "c",
      "cpp",
      "javascript",
      "typescript",
      "tsx",
      "bash",
      "html",
      "css",
      "markdown",
      "markdown_inline",
      "regex",
      "dockerfile",
      "astro",
      "toml",
      "vim",
      "vimdoc",
      "gitignore",
      "query",
    },
    highlight = { enable = true },
    incremental_selection = { enable = true },
    indent = { enable = true },
    autotag = { enable = true },
    context_commentstring = {
      enable = true,
      enable_autocmd = false,
    },
  },
}
